// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfpsbmipfhvdwatnahfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmcHNibWlwZmh2ZHdhdG5haGZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUyNzA2ODEsImV4cCI6MjA1MDg0NjY4MX0.gDrOJ4_VTijDTz8x4d9htTn5zvnAA4ZdPDoNUYBUHNA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);